-- Reference schema only. The application uses SQLAlchemy to create missing tables.
-- Do not run DROP/CREATE against an existing production database.

CREATE TABLE IF NOT EXISTS invoices (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number VARCHAR(120) NOT NULL UNIQUE,
    invoice_series VARCHAR(80) NOT NULL DEFAULT 'PVR/2026-27/',
    invoice_serial_number VARCHAR(80) NOT NULL,
    invoice_date DATE NOT NULL,
    customer_name VARCHAR(255) NOT NULL,
    customer_address TEXT,
    customer_gstin VARCHAR(30),
    booked_by VARCHAR(255),
    used_by VARCHAR(255),
    reference_number VARCHAR(255),
    cgst_rate DOUBLE PRECISION DEFAULT 0,
    sgst_rate DOUBLE PRECISION DEFAULT 0,
    igst_rate DOUBLE PRECISION DEFAULT 0,
    subtotal DOUBLE PRECISION DEFAULT 0,
    cgst DOUBLE PRECISION DEFAULT 0,
    sgst DOUBLE PRECISION DEFAULT 0,
    igst DOUBLE PRECISION DEFAULT 0,
    round_off DOUBLE PRECISION DEFAULT 0,
    grand_total DOUBLE PRECISION DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_invoices_invoice_number ON invoices(invoice_number);

CREATE TABLE IF NOT EXISTS trips (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id INTEGER NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
    ds_no VARCHAR(80), trip_date DATE, vehicle_type VARCHAR(100), vehicle_number VARCHAR(100),
    start_time VARCHAR(10), end_time VARCHAR(10), start_km DOUBLE PRECISION DEFAULT 0, end_km DOUBLE PRECISION DEFAULT 0,
    total_hours DOUBLE PRECISION DEFAULT 0, total_km DOUBLE PRECISION DEFAULT 0,
    slab_hours DOUBLE PRECISION DEFAULT 0, slab_km DOUBLE PRECISION DEFAULT 0, slab_rate DOUBLE PRECISION DEFAULT 0,
    extra_hour_rate DOUBLE PRECISION DEFAULT 0, extra_km_rate DOUBLE PRECISION DEFAULT 0,
    extra_hours DOUBLE PRECISION DEFAULT 0, extra_km DOUBLE PRECISION DEFAULT 0,
    extra_hour_amount DOUBLE PRECISION DEFAULT 0, extra_km_amount DOUBLE PRECISION DEFAULT 0,
    base_amount DOUBLE PRECISION DEFAULT 0, driver_bata DOUBLE PRECISION DEFAULT 0,
    parking DOUBLE PRECISION DEFAULT 0, toll DOUBLE PRECISION DEFAULT 0, other_charges DOUBLE PRECISION DEFAULT 0,
    trip_total DOUBLE PRECISION DEFAULT 0, notes TEXT
);

CREATE INDEX IF NOT EXISTS ix_trips_invoice_id ON trips(invoice_id);
